main: ca.nicbo.minecraftbut.youareachicken.YouAreAChicken
name: YouAreAChicken
version: ${project.version}
description: All players are chickens
author: Nicbo
api-version: 1.16
depend: [ LibsDisguises ]