main: ca.nicbo.minecraftbut.everyoneisachicken.EveryoneIsAChicken
name: EveryoneIsAChicken
version: ${project.version}
description: All players are chickens
author: Nicbo
api-version: 1.16
depend: [ LibsDisguises ]