main: ca.nicbo.minecraftbut.blockdropsarerandomlyassigned.BlockDropsAreRandomlyAssigned
name: BlockDropsAreRandomlyAssigned
version: ${project.version}
description: All drops from blocks are assigned to random items/loottables
author: Nicbo
api-version: 1.16